image: node:10.3.0

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - npm run lint
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
